// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskHub.API.Data;

#nullable disable

namespace TaskHub.API.Migrations
{
    [DbContext(typeof(TaskHubDbContext))]
    [Migration("20260305162638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskHub.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "კომპიუტერული ტექნიკა"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "პრინტერი"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "ქსელი"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "პროგრამული უზრუნველყოფა"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "ტელეფონი"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "სხვა"
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentID = 1,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestID = 2,
                            Text = "დამტკიცებულია, გადადეცა ტექნიკურ სამსახურს",
                            UserID = 2
                        },
                        new
                        {
                            CommentID = 2,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestID = 3,
                            Text = "პრობლემა მოგვარებულია - როუტერი გადაიტვირთა",
                            UserID = 3
                        },
                        new
                        {
                            CommentID = 3,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestID = 5,
                            Text = "ბიუჯეტი ამჟამად არ იძლევა საშუალებას",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.News", b =>
                {
                    b.Property<int>("NewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsID");

                    b.HasIndex("AuthorID");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsID = 1,
                            AuthorID = 4,
                            Content = "საქართველოს რკინიგზა შეიძენს 10 ახალ თანამედროვე მატარებელს. ყველა მატარებელი აღჭურვილი იქნება თანამედროვე კომფორტის სისტემებით.",
                            CreatedAt = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი მატარებლების დიეზა"
                        },
                        new
                        {
                            NewsID = 2,
                            AuthorID = 4,
                            Content = "თბილისი-ბათუმის მიმართულებით რკინიგზის მოდერნიზაციის სამუშაოები წარმატებით დასრულდა. განახლდა ლიანდაგი 150 კილომეტრის სიგრძეზე, რაც მნიშვნელოვნად გააუმჯობესებს მატარებლების მოძრაობის უსაფრთხოებას და კომფორტს. პროექტში ჩართული იყო 200-ზე მეტი სპეციალისტი და დასრულდა დაგეგმილ ვადებში. ახალი ლიანდაგი საშუალებას იძლევა მატარებლებმა განავითარონ უფრო მაღალი სიჩქარე უსაფრთხო პირობებში.",
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "რკინიგზის მოდერნიზაცია დასრულდა"
                        },
                        new
                        {
                            NewsID = 3,
                            AuthorID = 2,
                            Content = "დანერგილია უახლესი ციფრული დისპეტჩერული სისტემა, რომელიც რეალურ დროში აკონტროლებს ყველა მატარებლის მდებარეობას.",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი დისპეტჩერული სისტემა"
                        },
                        new
                        {
                            NewsID = 4,
                            AuthorID = 4,
                            Content = "საქართველოს რკინიგზამ დანერგა საერთაშორისო უსაფრთხოების სტანდარტები, რომელიც მოიცავს ახალ სიგნალიზაციის სისტემებს, გაუმჯობესებულ აპარატურას და თანამშრომელთა რეგულარულ ტრენინგებს. ამ ცვლილებებით მნიშვნელოვნად შემცირდება ავარიების რისკი და გაიზრდება მგზავრთა უსაფრთხოება. სისტემა შემუშავებულია ევროპის წამყვან კომპანიებთან თანამშრობით.",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "უსაფრთხოების ახალი სტანდარტები"
                        },
                        new
                        {
                            NewsID = 5,
                            AuthorID = 2,
                            Content = "2026 წლის ზაფხულიდან დაიწყება ელექტრო მატარებლების ექსპლუატაცია თბილისის მიმართულებით.",
                            CreatedAt = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ელექტრო მატარებლები გზაზე"
                        },
                        new
                        {
                            NewsID = 6,
                            AuthorID = 4,
                            Content = "ჩატარდა საერთაშორისო ტრენინგი რკინიგზის 150 თანამშრომლისთვის. ტრენინგი მოიცავდა უსაფრთხოების ახალ პროტოკოლებს, თანამედროვე ტექნოლოგიების გამოყენებას და საავარიო სიტუაციებში მოქმედების გზებს. ლექტორები იყვნენ გერმანიისა და საფრანგეთის წამყვანი სპეციალისტები.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "რკინიგზის მუშაკთა ტრენინგი"
                        },
                        new
                        {
                            NewsID = 7,
                            AuthorID = 2,
                            Content = "შევიდა 20 ახალი თანამედროვე სამგზავრო ვაგონი ევროპული სტანდარტებით.",
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი ვაგონები"
                        },
                        new
                        {
                            NewsID = 8,
                            AuthorID = 4,
                            Content = "დაიწყო მთავარი სადგურების რეკონსტრუქცია. პროექტი მოიცავს თბილისის, ბათუმისა და ქუთაისის სადგურების სრულ განახლებას. დამონტაჟდება თანამედროვე ინფორმაციული ტაბლოები, განახლდება მოლოდინის დარბაზები და გაუმჯობესდება ინფრასტრუქტურა. რეკონსტრუქცია დასრულდება 2026 წლის ბოლოსთვის.",
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "სადგურების რეკონსტრუქცია"
                        },
                        new
                        {
                            NewsID = 9,
                            AuthorID = 2,
                            Content = "ყველა საერთაშორისო და საშინაო მიმართულების მატარებელს დაემატება უფასო WiFi.",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "WiFi ყველა მატარებელში"
                        },
                        new
                        {
                            NewsID = 10,
                            AuthorID = 4,
                            Content = "დაემატება ახალი სეზონური მარშრუტი თბილისი-მესტია, რომელიც იმუშავებს ზამთრის სეზონში. მარშრუტი გაივლის ცხინვალის რეგიონს და იქნება ერთ-ერთი ულამაზესი სარკინიგზო მიმართულება საქართველოში. მატარებელი იქნება აღჭურვილი თანამედროვე კომფორტის ყველა საშუალებით.",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი მარშრუტი - თბილისი-მესტია"
                        },
                        new
                        {
                            NewsID = 11,
                            AuthorID = 2,
                            Content = "რკინიგზა იწყებს მწვანე ინიციატივას - ნახშირბადის გამონაბოლქვის შემცირების პროგრამას.",
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ეკოლოგიური ინიციატივა"
                        },
                        new
                        {
                            NewsID = 12,
                            AuthorID = 4,
                            Content = "დაინერგა მობილური აპლიკაცია ბილეთების შესაძენად. აპლიკაცია საშუალებას აძლევს მომხმარებლებს დაჯავშნონ ადგილები, გადაიხადონ ონლაინ და მიიღონ ციფრული ბილეთები. ასევე ხელმისაწვდომია ისტორია და ბონუსების სისტემა ლოიალური მომხმარებლებისთვის. სისტემა მუშაობს როგორც iOS, ასევე Android პლატფორმებზე.",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი ბილეთების სისტემა"
                        },
                        new
                        {
                            NewsID = 13,
                            AuthorID = 2,
                            Content = "აპრილიდან ამოქმედდება საზაფხულო განრიგი გაზრდილი რეისებით პოპულარულ მიმართულებებზე.",
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "საზაფხულო განრიგის ცვლილება"
                        },
                        new
                        {
                            NewsID = 14,
                            AuthorID = 4,
                            Content = "ხელი მოეწერა მემორანდუმს თურქეთის და აზერბაიჯანის რკინიგზებთან რეგიონული სატრანსპორტო დერეფნის განსავითარებლად. თანამშრომლობა მოიცავს ტექნოლოგიების გაცვლას, ერთობლივ პროექტებს და საერთაშორისო მარშრუტების გაფართოებას.",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "საერთაშორისო თანამშრომლობა"
                        },
                        new
                        {
                            NewsID = 15,
                            AuthorID = 2,
                            Content = "დაინერგა ახალი შეღავათიანი სისტემა სტუდენტებისთვის - 50% ფასდაკლება სემესტრის განმავლობაში.",
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "შეღავათები სტუდენტებისთვის"
                        },
                        new
                        {
                            NewsID = 16,
                            AuthorID = 4,
                            Content = "დაიწყო ახალი სარკინიგზო ხიდის მშენებლობა მტკვარზე. პროექტი განხორციელდება თანამედროვე ინჟინერიული გადაწყვეტილებებით და უზრუნველყოფს უფრო სწრაფ და უსაფრთხო მიმოსვლას. ხიდი გამოირჩევა უნიკალური არქიტექტურული დიზაინით და გახდება თბილისის ახალი ღირსშესანიშნაობა. მშენებლობა დასრულდება 2027 წლის გაზაფხულზე.",
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი სამშენებლო პროექტი"
                        },
                        new
                        {
                            NewsID = 17,
                            AuthorID = 2,
                            Content = "დეკემბრის განმავლობაში მოქმედებს სპეციალური საშობაო ფასები ოჯახური ბილეთებისთვის.",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "საშობაო აქცია"
                        },
                        new
                        {
                            NewsID = 18,
                            AuthorID = 4,
                            Content = "გაიხსნა ულტრათანამედროვე დიაგნოსტიკის ცენტრი, სადაც რეგულარულად ტარდება მატარებლების ტექნიკური შემოწმება და მოვლა. ცენტრი აღჭურვილია უახლესი ტექნოლოგიით და საშუალებას იძლევა დროულად გამოვლინდეს ნებისმიერი ტექნიკური პრობლემა.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "რკინიგზის ცენტრალური დიაგნოსტიკის ცენტრი"
                        },
                        new
                        {
                            NewsID = 19,
                            AuthorID = 2,
                            Content = "გაიხსნა ახალი სატვირთო მიმართულებები რეგიონში, რაც გააძლიერებს ეკონომიკურ კავშირებს.",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ახალი სატვირთო მარშრუტები"
                        },
                        new
                        {
                            NewsID = 20,
                            AuthorID = 4,
                            Content = "საქართველოს რკინიგზა აღნიშნავს 70 წლის იუბილეს. ამ პერიოდში გავლილია გრძელი და საინტერესო გზა - საბჭოთა პერიოდის რკინიგზიდან დღევანდელ თანამედროვე ევროპულ სტანდარტებამდე. იუბილესთან დაკავშირებით დაგეგმილია სპეციალური ღონისძიებები და გამოფენები, სადაც წარმოდგენილი იქნება რკინიგზის ისტორია და მომავლის გეგმები. მოხდება ვეტერანების დაჯილდოება და გაიხსნება ახალი რკინიგზის მუზეუმი.",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "70 წლის იუბილე"
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.Request", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiatorID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("InitiatorID");

                    b.HasIndex("StatusID");

                    b.HasIndex("SubcategoryID");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RequestID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "საჭიროა ახალი ლეპტოპი პროექტის მენეჯერისთვის",
                            InitiatorID = 1,
                            StatusID = 2,
                            SubcategoryID = 1,
                            UpdatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestID = 2,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "პრინტერის კარტრიჯი ამოიწურა, საჭიროა შეცვლა",
                            InitiatorID = 1,
                            StatusID = 3,
                            SubcategoryID = 4,
                            UpdatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestID = 3,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ინტერნეტ კავშირი არ მუშაობს მე-3 სართულზე",
                            InitiatorID = 1,
                            StatusID = 5,
                            SubcategoryID = 7,
                            UpdatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestID = 4,
                            CategoryID = 4,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Microsoft Office-ის ინსტალაცია ახალ კომპიუტერზე",
                            InitiatorID = 1,
                            StatusID = 4,
                            SubcategoryID = 10,
                            UpdatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestID = 5,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "დამატებითი მონიტორი",
                            InitiatorID = 1,
                            StatusID = 6,
                            SubcategoryID = 2,
                            UpdatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.RequestParticipant", b =>
                {
                    b.Property<int>("RequestParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestParticipantID"));

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RequestParticipantID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.ToTable("RequestParticipants");

                    b.HasData(
                        new
                        {
                            RequestParticipantID = 1,
                            RequestID = 1,
                            Role = "შემვსები",
                            UserID = 1
                        },
                        new
                        {
                            RequestParticipantID = 2,
                            RequestID = 2,
                            Role = "შემვსები",
                            UserID = 1
                        },
                        new
                        {
                            RequestParticipantID = 3,
                            RequestID = 2,
                            Role = "ხელმძღვანელი",
                            UserID = 2
                        },
                        new
                        {
                            RequestParticipantID = 4,
                            RequestID = 2,
                            Role = "შემსრულებელი",
                            UserID = 3
                        },
                        new
                        {
                            RequestParticipantID = 5,
                            RequestID = 3,
                            Role = "შემვსები",
                            UserID = 1
                        },
                        new
                        {
                            RequestParticipantID = 6,
                            RequestID = 3,
                            Role = "ხელმძღვანელი",
                            UserID = 2
                        },
                        new
                        {
                            RequestParticipantID = 7,
                            RequestID = 3,
                            Role = "შემსრულებელი",
                            UserID = 3
                        },
                        new
                        {
                            RequestParticipantID = 8,
                            RequestID = 4,
                            Role = "შემვსები",
                            UserID = 1
                        },
                        new
                        {
                            RequestParticipantID = 9,
                            RequestID = 4,
                            Role = "ხელმძღვანელი",
                            UserID = 2
                        },
                        new
                        {
                            RequestParticipantID = 10,
                            RequestID = 4,
                            Role = "შემსრულებელი",
                            UserID = 3
                        },
                        new
                        {
                            RequestParticipantID = 11,
                            RequestID = 5,
                            Role = "შემვსები",
                            UserID = 1
                        },
                        new
                        {
                            RequestParticipantID = 12,
                            RequestID = 5,
                            Role = "ხელმძღვანელი",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            StatusClass = "new",
                            StatusName = "ახალი"
                        },
                        new
                        {
                            StatusID = 2,
                            StatusClass = "pending",
                            StatusName = "დამტკიცების მოლოდინში"
                        },
                        new
                        {
                            StatusID = 3,
                            StatusClass = "approved",
                            StatusName = "დამტკიცებული"
                        },
                        new
                        {
                            StatusID = 4,
                            StatusClass = "inprogress",
                            StatusName = "შესრულების პროცესში"
                        },
                        new
                        {
                            StatusID = 5,
                            StatusClass = "completed",
                            StatusName = "შესრულებული"
                        },
                        new
                        {
                            StatusID = 6,
                            StatusClass = "rejected",
                            StatusName = "უარყოფილი"
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            CategoryID = 1,
                            SubcategoryName = "ლეპტოპი"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            CategoryID = 1,
                            SubcategoryName = "მონიტორი"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            CategoryID = 1,
                            SubcategoryName = "კლავიატურა/მაუსი"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            CategoryID = 2,
                            SubcategoryName = "კარტრიჯის შეცვლა"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            CategoryID = 2,
                            SubcategoryName = "შეკეთება"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            CategoryID = 2,
                            SubcategoryName = "ახალი პრინტერი"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            CategoryID = 3,
                            SubcategoryName = "ინტერნეტ კავშირი"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            CategoryID = 3,
                            SubcategoryName = "WiFi პრობლემა"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            CategoryID = 3,
                            SubcategoryName = "ქსელის კონფიგურაცია"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            CategoryID = 4,
                            SubcategoryName = "ინსტალაცია"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            CategoryID = 4,
                            SubcategoryName = "განახლება"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            CategoryID = 4,
                            SubcategoryName = "ლიცენზია"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            CategoryID = 5,
                            SubcategoryName = "ახალი ტელეფონი"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            CategoryID = 5,
                            SubcategoryName = "შეკეთება"
                        },
                        new
                        {
                            SubcategoryID = 15,
                            CategoryID = 5,
                            SubcategoryName = "SIM ბარათი"
                        },
                        new
                        {
                            SubcategoryID = 16,
                            CategoryID = 6,
                            SubcategoryName = "სხვა"
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AvatarClass = "avatar-blue",
                            Department = "IT დეპარტამენტი",
                            Email = "g.maisuradze@railway.ge",
                            Initials = "გმ",
                            Name = "გიორგი მაისურაძე",
                            Password = "password1",
                            Phone = "+995 599 123 456",
                            Role = "შემვსები",
                            Title = "პროექტის მენეჯერი"
                        },
                        new
                        {
                            UserID = 2,
                            AvatarClass = "avatar-green",
                            Department = "IT დეპარტამენტი",
                            Email = "n.beridze@railway.ge",
                            Initials = "ნბ",
                            Name = "ნინო ბერიძე",
                            Password = "password2",
                            Phone = "+995 577 234 567",
                            Role = "ხელმძღვანელი",
                            Title = "დეპარტამენტის ხელმძღვანელი"
                        },
                        new
                        {
                            UserID = 3,
                            AvatarClass = "avatar-orange",
                            Department = "ტექნიკური სამსახური",
                            Email = "d.kvaratskhelia@railway.ge",
                            Initials = "დკ",
                            Name = "დავით კვარაცხელია",
                            Password = "password3",
                            Phone = "+995 555 345 678",
                            Role = "შემსრულებელი",
                            Title = "ტექნიკური სპეციალისტი"
                        },
                        new
                        {
                            UserID = 4,
                            AvatarClass = "avatar-red",
                            Department = "ადმინისტრაცია",
                            Email = "m.gelashvili@railway.ge",
                            Initials = "მგ",
                            Name = "მარიამ გელაშვილი",
                            Password = "admin123",
                            Phone = "+995 591 456 789",
                            Role = "ადმინისტრატორი",
                            Title = "სისტემის ადმინისტრატორი"
                        });
                });

            modelBuilder.Entity("TaskHub.API.Models.Vacancy", b =>
                {
                    b.Property<int>("VacancyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacancyID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacancyID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("TaskHub.API.Models.Comment", b =>
                {
                    b.HasOne("TaskHub.API.Models.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskHub.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskHub.API.Models.News", b =>
                {
                    b.HasOne("TaskHub.API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskHub.API.Models.Request", b =>
                {
                    b.HasOne("TaskHub.API.Models.Category", "Category")
                        .WithMany("Requests")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskHub.API.Models.User", "Initiator")
                        .WithMany("InitiatedRequests")
                        .HasForeignKey("InitiatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskHub.API.Models.Status", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskHub.API.Models.Subcategory", "Subcategory")
                        .WithMany("Requests")
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Initiator");

                    b.Navigation("Status");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("TaskHub.API.Models.RequestParticipant", b =>
                {
                    b.HasOne("TaskHub.API.Models.Request", "Request")
                        .WithMany("Participants")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskHub.API.Models.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskHub.API.Models.Subcategory", b =>
                {
                    b.HasOne("TaskHub.API.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TaskHub.API.Models.Vacancy", b =>
                {
                    b.HasOne("TaskHub.API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskHub.API.Models.Category", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("TaskHub.API.Models.Request", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TaskHub.API.Models.Status", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TaskHub.API.Models.Subcategory", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TaskHub.API.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("InitiatedRequests");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
