// NOTE: This migration was generated by EF Core for SQL Server.
// If your project uses a different database provider, regenerate it with:
//   dotnet ef migrations add AddDigestEntries
// after adding the DbSet and model changes described in INSTRUCTIONS.md.
//
// If you ARE using SQL Server and already have EF migrations set up,
// you can copy this file into your Migrations folder, then run:
//   dotnet ef database update

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YourProject.API.Migrations   // REPLACE with your actual namespace
{
    public partial class AddDigestEntries : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DigestEntries",
                columns: table => new
                {
                    DigestEntryID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ImageUrl = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SourceName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SourceUrl = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PeriodFrom = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PeriodTo = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsFeatured = table.Column<bool>(type: "bit", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    AuthorID = table.Column<int>(type: "int", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DigestEntries", x => x.DigestEntryID);
                    table.ForeignKey(
                        name: "FK_DigestEntries_Users_AuthorID",
                        column: x => x.AuthorID,
                        principalTable: "Users",       // ADJUST if your users table has a different name
                        principalColumn: "UserID",     // ADJUST if your user PK column has a different name
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DigestEntries_AuthorID",
                table: "DigestEntries",
                column: "AuthorID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "DigestEntries");
        }
    }
}
